import { ChangeDetectionStrategy, Component, computed, effect, inject, input, signal, untracked } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatDialog } from '@angular/material/dialog';

import { ApiService } from '../../core/api.service';
import { NotifyService } from '../../core/notify.service';
import { ConfirmDialogComponent } from '../../shared/confirm-dialog';
import { ColumnFilter, FilterOperator } from '../../core/models';

const PAGE_SIZE = 50;

interface FilterRow {
  column: string;
  operator: FilterOperator;
  value: string;
}

/** Operators offered in the filter bar, in display order. */
export const FILTER_OPERATORS: { value: FilterOperator; label: string; needsValue: boolean }[] = [
  { value: 'EQ',       label: '=',            needsValue: true },
  { value: 'NEQ',      label: '≠',            needsValue: true },
  { value: 'CONTAINS', label: 'contains',     needsValue: true },
  { value: 'STARTS',   label: 'starts with',  needsValue: true },
  { value: 'ENDS',     label: 'ends with',    needsValue: true },
  { value: 'GT',       label: '>',            needsValue: true },
  { value: 'GTE',      label: '≥',            needsValue: true },
  { value: 'LT',       label: '<',            needsValue: true },
  { value: 'LTE',      label: '≤',            needsValue: true },
  { value: 'NULL',     label: 'is null',      needsValue: false },
  { value: 'NOTNULL',  label: 'is not null',  needsValue: false },
];

/** Paginated, sortable, inline-editable grid for a single table's data. */
@Component({
  selector: 'app-data-grid',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule, MatButtonModule, MatIconModule, MatProgressBarModule, MatTooltipModule],
  templateUrl: './data-grid.html',
  styleUrl: './data-grid.scss',
})
export class DataGridComponent {
  private readonly api = inject(ApiService);
  private readonly notify = inject(NotifyService);
  private readonly dialog = inject(MatDialog);

  readonly table = input.required<string>();

  readonly loading = signal(false);
  readonly error = signal('');
  readonly columns = signal<string[]>([]);
  readonly pk = signal<string[]>([]);
  readonly can = signal({ insert: false, update: false, delete: false });
  readonly total = signal(0);
  readonly page = signal(0);
  readonly sort = signal<string | null>(null);
  readonly dir = signal<'ASC' | 'DESC'>('ASC');

  // ---- column filtering ----
  readonly operators = FILTER_OPERATORS;
  readonly showFilters = signal(false);
  /** Draft filter rows being edited in the filter bar. */
  readonly filterDraft = signal<FilterRow[]>([]);
  /** Filters currently applied to the fetched data. */
  readonly appliedFilters = signal<ColumnFilter[]>([]);

  /** Pristine rows from the server (used for diffing on save). */
  private original: any[][] = [];
  /** Editable working copy bound to the inputs. */
  readonly working = signal<any[][]>([]);
  readonly newRows = signal<Record<string, string>[]>([]);
  readonly deleted = signal<Set<number>>(new Set());
  readonly dirty = signal<Set<number>>(new Set());
  readonly pkInfo = signal<Record<string, { autoGenerated: boolean; nextValue?: number }>>({});

  readonly pageSize = PAGE_SIZE;
  readonly canUpdate = computed(() => this.can().update && this.pk().length > 0);
  readonly canDelete = computed(() => this.can().delete && this.pk().length > 0);
  readonly canInsert = computed(() => this.can().insert);
  readonly showActions = computed(() => this.canDelete() || this.canInsert());
  readonly fromRow = computed(() => (this.working().length ? this.page() * PAGE_SIZE + 1 : 0));
  readonly toRow = computed(() => this.page() * PAGE_SIZE + this.working().length);
  readonly hasPrev = computed(() => this.page() > 0);
  readonly hasNext = computed(() => (this.page() + 1) * PAGE_SIZE < this.total());
  readonly hasChanges = computed(() => this.newRows().length > 0 || this.dirty().size > 0 || this.deleted().size > 0);
  readonly activeFilterCount = computed(() => this.appliedFilters().length);

  constructor() {
    // Reload from page 0 whenever the bound table changes.
    effect(() => {
      this.table();
      untracked(() => {
        this.sort.set(null);
        this.dir.set('ASC');
        this.page.set(0);
        this.appliedFilters.set([]);
        this.filterDraft.set([]);
        this.showFilters.set(false);
        this.fetch();
      });
    });
  }

  operatorNeedsValue(op: FilterOperator): boolean {
    return this.operators.find(o => o.value === op)?.needsValue ?? true;
  }

  toggleFilters(): void {
    this.showFilters.update(v => !v);
    if (this.showFilters() && this.filterDraft().length === 0) this.addFilter();
  }

  addFilter(): void {
    const firstCol = this.columns()[0] ?? '';
    this.filterDraft.update(rows => [...rows, { column: firstCol, operator: 'CONTAINS', value: '' }]);
  }

  removeFilter(index: number): void {
    this.filterDraft.update(rows => rows.filter((_, i) => i !== index));
  }

  /** Validate, normalize and apply the draft filters, then reload from page 0. */
  applyFilters(): void {
    const valid = this.filterDraft()
      .filter(r => r.column && (this.operatorNeedsValue(r.operator) ? r.value !== '' : true))
      .map<ColumnFilter>(r => ({
        column: r.column,
        operator: r.operator,
        value: this.operatorNeedsValue(r.operator) ? r.value : '',
      }));
    this.appliedFilters.set(valid);
    this.page.set(0);
    this.fetch();
  }

  clearFilters(): void {
    this.filterDraft.set([]);
    this.appliedFilters.set([]);
    this.showFilters.set(false);
    this.page.set(0);
    this.fetch();
  }

  /** Public hook so the parent can refresh after a Sync. */
  reload(): void {
    this.fetch();
  }

  isPk(col: string): boolean {
    return this.pk().includes(col.toUpperCase());
  }

  private fetch(): void {
    const table = this.table();
    this.loading.set(true);
    this.error.set('');
    this.api.browse(table, this.page(), PAGE_SIZE, this.sort(), this.dir(), this.appliedFilters()).subscribe({
      next: res => {
        if (res.error) { this.error.set(res.error); this.loading.set(false); return; }
        this.columns.set(res.result.columns ?? []);
        this.pk.set((res.pkColumns ?? []).map(c => String(c).toUpperCase()));
        this.can.set(res.can ?? { insert: false, update: false, delete: false });
        this.total.set(res.total);
        this.original = (res.result.rows ?? []).map(r => r.slice());
        this.working.set(this.original.map(r => r.slice()));
        this.newRows.set([]);
        this.deleted.set(new Set());
        this.dirty.set(new Set());
        this.loading.set(false);
        // Fetch PK generation info for insert hints
        if (res.can?.insert) {
          this.api.pkNextInfo(table).subscribe({ next: info => this.pkInfo.set(info), error: () => {} });
        }
      },
      error: err => {
        this.loading.set(false);
        this.error.set(err?.error?.error || 'Failed to load data');
      },
    });
  }

  toggleSort(col: string): void {
    if (this.sort()?.toUpperCase() === col.toUpperCase()) {
      this.dir.set(this.dir() === 'ASC' ? 'DESC' : 'ASC');
    } else {
      this.sort.set(col);
      this.dir.set('ASC');
    }
    this.page.set(0);
    this.fetch();
  }

  prev(): void { if (this.hasPrev()) { this.page.update(p => p - 1); this.fetch(); } }
  next(): void { if (this.hasNext()) { this.page.update(p => p + 1); this.fetch(); } }

  addRow(): void {
    this.newRows.update(rows => [{ ...this.blankRow() }, ...rows]);
  }
  discardNew(index: number): void {
    this.newRows.update(rows => rows.filter((_, i) => i !== index));
  }
  private blankRow(): Record<string, string> {
    const r: Record<string, string> = {};
    const info = this.pkInfo();
    this.columns().forEach(c => {
      const colInfo = info[c.toUpperCase()];
      if (colInfo && !colInfo.autoGenerated && colInfo.nextValue != null) {
        r[c] = String(colInfo.nextValue);
      } else {
        r[c] = '';
      }
    });
    return r;
  }

  isPkAutoGenerated(col: string): boolean {
    const info = this.pkInfo()[col.toUpperCase()];
    return !!info?.autoGenerated;
  }

  pkPlaceholder(col: string): string {
    const info = this.pkInfo()[col.toUpperCase()];
    if (!info) return col;
    if (info.autoGenerated) return 'auto';
    return info.nextValue != null ? String(info.nextValue) : col;
  }

  onCellChange(ri: number): void {
    this.dirty.update(set => new Set(set).add(ri));
  }

  toggleDelete(ri: number): void {
    this.deleted.update(set => {
      const next = new Set(set);
      next.has(ri) ? next.delete(ri) : next.add(ri);
      return next;
    });
  }

  /** Persist all pending inserts, updates and deletes, then reload. */
  async save(): Promise<void> {
    const table = this.table();
    const cols = this.columns();
    const colIndex = new Map(cols.map((c, i) => [c.toUpperCase(), i]));
    // Bulk delete confirmation
    if (this.deleted().size > 0) {
      const confirmed = await firstValueFrom(
        this.dialog.open(ConfirmDialogComponent, {
          data: { message: `Delete ${this.deleted().size} row(s)? This cannot be undone.` },
          width: '480px',
        }).afterClosed(),
      );
      if (!confirmed) return;
    }

    interface OpMeta { label: string; promise: Promise<unknown>; }
    const opsMeta: OpMeta[] = [];

    // INSERTs — only include non-empty values.
    let insertIdx = 1;
    for (const nr of this.newRows()) {
      const values: Record<string, string> = {};
      for (const c of cols) if (nr[c] !== '') values[c] = nr[c];
      if (Object.keys(values).length) {
        opsMeta.push({ label: `INSERT #${insertIdx}`, promise: firstValueFrom(this.api.insertRow(table, values)) });
      }
      insertIdx++;
    }

    // UPDATEs — diff working vs. original for dirty, non-deleted rows.
    for (const ri of this.dirty()) {
      if (this.deleted().has(ri)) continue;
      const values: Record<string, any> = {};
      cols.forEach((c, ci) => {
        if (this.isPk(c)) return;
        const orig = this.original[ri][ci];
        const origStr = orig === null || orig === undefined ? '' : String(orig);
        const cur = this.working()[ri][ci];
        const curStr = cur === null || cur === undefined ? '' : String(cur);
        if (curStr !== origStr) values[c] = cur;
      });
      if (Object.keys(values).length) {
        opsMeta.push({ label: `UPDATE row ${ri + 1}`, promise: firstValueFrom(this.api.updateRow(table, this.keyFor(ri, colIndex), values)) });
      }
    }

    // DELETEs
    for (const ri of this.deleted()) {
      opsMeta.push({ label: `DELETE row ${ri + 1}`, promise: firstValueFrom(this.api.deleteRow(table, this.keyFor(ri, colIndex))) });
    }

    const ops = opsMeta.map(m => m.promise);
    if (ops.length === 0) { this.notify.warn('Nothing to save'); return; }

    const settled = await Promise.allSettled(ops);
    const failedDetails: string[] = [];
    settled.forEach((s, i) => {
      if (s.status === 'rejected') {
        const reason = (s as PromiseRejectedResult).reason?.error?.error || 'unknown error';
        failedDetails.push(`${opsMeta[i].label}: ${reason}`);
      }
    });
    if (failedDetails.length) {
      this.notify.warn(`Saved ${ops.length - failedDetails.length}, failed ${failedDetails.length}: ${failedDetails.join(' | ')}`);
    } else {
      this.notify.success(`Saved ${ops.length} change(s)`);
    }
    this.fetch();
  }

  private keyFor(ri: number, colIndex: Map<string, number>): Record<string, any> {
    const key: Record<string, any> = {};
    for (const p of this.pk()) {
      const idx = colIndex.get(p);
      if (idx === undefined) {
        throw new Error(`Primary key column "${p}" not found in column list for row ${ri}`);
      }
      key[p] = this.original[ri][idx];
    }
    return key;
  }

  // NOTE (issue #5): inputTypeFor() is not implemented because data-grid only has
  // column names (strings), not column type metadata. Type info lives in the parent
  // table-detail's `detail` signal. Adding a date/time input type would require
  // passing column type info as an input — skipped to avoid significant refactoring.
}
