-- ============================================================
--  Audit log table for Oracle Schema Explorer
--  The app auto-creates this on startup (dbexplorer.audit.auto-create-table=true),
--  but you can create it manually with the right grants if you prefer.
-- ============================================================

-- ---- Oracle 12c and newer (IDENTITY column) ----
CREATE TABLE DBX_AUDIT_LOG (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username     VARCHAR2(128),   -- who performed the action
  action       VARCHAR2(64),    -- LOGIN, RUN_SQL, INSERT_ROW, UPDATE_ROW, DELETE_ROW, ...
  target       VARCHAR2(256),   -- the table / object the action touched
  detail       VARCHAR2(4000),  -- the SQL text, affected key, columns, etc.
  success      CHAR(1),         -- 'Y' if HTTP status < 400, else 'N'
  http_status  NUMBER(5),
  client_ip    VARCHAR2(64),
  duration_ms  NUMBER(12),      -- how long the request took
  event_time   TIMESTAMP        -- when it happened
);
CREATE INDEX DBX_AUDIT_LOG_TIME_IX ON DBX_AUDIT_LOG (event_time);

-- ---- Oracle 11g alternative (no IDENTITY): use a sequence + trigger ----
-- CREATE TABLE DBX_AUDIT_LOG (
--   id NUMBER PRIMARY KEY, username VARCHAR2(128), action VARCHAR2(64),
--   target VARCHAR2(256), detail VARCHAR2(4000), success CHAR(1),
--   http_status NUMBER(5), client_ip VARCHAR2(64), duration_ms NUMBER(12),
--   event_time TIMESTAMP
-- );
-- CREATE SEQUENCE DBX_AUDIT_SEQ;
-- CREATE OR REPLACE TRIGGER DBX_AUDIT_BI BEFORE INSERT ON DBX_AUDIT_LOG
--   FOR EACH ROW WHEN (NEW.id IS NULL)
--   BEGIN :NEW.id := DBX_AUDIT_SEQ.NEXTVAL; END;
-- /
-- (On 11g, set dbexplorer.audit.auto-create-table=false and run this script yourself.)
