-- 1. Users Table
CREATE TABLE DBX_USERS (
    USERNAME VARCHAR2(50) PRIMARY KEY,
    PASSWORD VARCHAR2(255) NOT NULL, -- Supports {noop} or BCrypt
    ROLE VARCHAR2(20) DEFAULT 'USER',
    ENABLED CHAR(1) DEFAULT 'Y'
);

-- 2. User Privileges (SELECT, INSERT, UPDATE, DELETE, EXECUTE_SQL)
CREATE TABLE DBX_USER_PRIVILEGES (
    USERNAME VARCHAR2(50),
    PRIVILEGE VARCHAR2(50),
    CONSTRAINT FK_PRIV_USER FOREIGN KEY (USERNAME) REFERENCES DBX_USERS(USERNAME) ON DELETE CASCADE,
    PRIMARY KEY (USERNAME, PRIVILEGE)
);

-- 3. Allowed Tables (Whitelist)
CREATE TABLE DBX_USER_ALLOWED_TABLES (
    USERNAME VARCHAR2(50),
    TABLE_NAME VARCHAR2(128),
    CONSTRAINT FK_TABLE_USER FOREIGN KEY (USERNAME) REFERENCES DBX_USERS(USERNAME) ON DELETE CASCADE,
    PRIMARY KEY (USERNAME, TABLE_NAME)
);

-- 4. Row-Level Filters
CREATE TABLE DBX_USER_TABLE_FILTERS (
    USERNAME VARCHAR2(50),
    TABLE_NAME VARCHAR2(128),
    FILTER_CONDITION VARCHAR2(4000), -- The SQL WHERE snippet
    CONSTRAINT FK_FILTER_USER FOREIGN KEY (USERNAME) REFERENCES DBX_USERS(USERNAME) ON DELETE CASCADE,
    PRIMARY KEY (USERNAME, TABLE_NAME)
);

-- Initial Data (Admin)
-- NOTE: The application creates the admin account automatically on first run with a
-- randomly generated BCrypt-hashed password printed once to stdout. Do NOT seed a
-- hardcoded password here — run the app and copy the password from the startup log.
INSERT INTO DBX_USER_PRIVILEGES (USERNAME, PRIVILEGE) VALUES ('admin', 'SELECT');
INSERT INTO DBX_USER_PRIVILEGES (USERNAME, PRIVILEGE) VALUES ('admin', 'INSERT');
INSERT INTO DBX_USER_PRIVILEGES (USERNAME, PRIVILEGE) VALUES ('admin', 'UPDATE');
INSERT INTO DBX_USER_PRIVILEGES (USERNAME, PRIVILEGE) VALUES ('admin', 'DELETE');
INSERT INTO DBX_USER_PRIVILEGES (USERNAME, PRIVILEGE) VALUES ('admin', 'EXECUTE_SQL');

-- Initial Data (Analyst Example — replace {noop}analyst123 with a real BCrypt hash before use)
INSERT INTO DBX_USERS (USERNAME, PASSWORD, ROLE) VALUES ('analyst', '{REPLACE_WITH_BCRYPT_HASH}', 'ANALYST');
INSERT INTO DBX_USER_PRIVILEGES (USERNAME, PRIVILEGE) VALUES ('analyst', 'SELECT');
INSERT INTO DBX_USER_PRIVILEGES (USERNAME, PRIVILEGE) VALUES ('analyst', 'INSERT');
INSERT INTO DBX_USER_PRIVILEGES (USERNAME, PRIVILEGE) VALUES ('analyst', 'UPDATE');
INSERT INTO DBX_USER_PRIVILEGES (USERNAME, PRIVILEGE) VALUES ('analyst', 'DELETE');
INSERT INTO DBX_USER_ALLOWED_TABLES (USERNAME, TABLE_NAME) VALUES ('analyst', 'BPM_PROCESSES_INFO');
INSERT INTO DBX_USER_ALLOWED_TABLES (USERNAME, TABLE_NAME) VALUES ('analyst', 'DS_HOME_COMPONENT');
INSERT INTO DBX_USER_ALLOWED_TABLES (USERNAME, TABLE_NAME) VALUES ('analyst', 'BPM_TRANS_STEPS');
INSERT INTO DBX_USER_TABLE_FILTERS (USERNAME, TABLE_NAME, FILTER_CONDITION) VALUES ('analyst', 'BPM_PROCESSES_INFO', 'PLATFORM_CODE = ''AQARI''');
INSERT INTO DBX_USER_TABLE_FILTERS (USERNAME, TABLE_NAME, FILTER_CONDITION) VALUES ('analyst', 'DS_HOME_COMPONENT', 'PLATFORM_CODE = ''AQARI''');
INSERT INTO DBX_USER_TABLE_FILTERS (USERNAME, TABLE_NAME, FILTER_CONDITION) VALUES ('analyst', 'BPM_TRANS_STEPS', 'ORDER_C > 3');

COMMIT;
