import { HttpClient, HttpEvent, HttpParams } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import {
  AdminUserDetail, AdminUserSummary, ColumnFilter, ComponentInfoLookup, ConfirmationScreenConfigDto,
  CrudListResponse, CrudRow, DataPage, DbObject, FeeDto, Fingerprint,
  Insights, LookupItem, Me, ObjectType, ProcessInfoDto,
  QueryResult, RelatedDeptDto, RequiredDocDto, SaveUserRequest, SchemaOverview, ScreenInfoLookup,
  ServiceConfigPayload, ServiceListResponse, SourceCode, StepDto, TableDetail,
  TargetAudienceDto, TargetAudienceLookup, UploadResult,
} from './models';

/** Single gateway for every backend call. Keeps URLs and shapes in one place. */
@Injectable({ providedIn: 'root' })
export class ApiService {
  private readonly http = inject(HttpClient);

  // ---- auth ----
  login(username: string, password: string): Observable<Me> {
    return this.http.post<Me>('/api/login', { username, password });
  }
  logout(): Observable<{ ok: boolean }> {
    return this.http.post<{ ok: boolean }>('/api/logout', {});
  }
  me(): Observable<Me> {
    return this.http.get<Me>('/api/me');
  }

  // ---- schema ----
  overview(): Observable<SchemaOverview> {
    return this.http.get<SchemaOverview>('/api/schema');
  }
  fingerprint(): Observable<Fingerprint> {
    return this.http.get<Fingerprint>('/api/schema/fingerprint');
  }
  objects(type: ObjectType): Observable<DbObject[]> {
    return this.http.get<DbObject[]>('/api/schema/objects', { params: { type } });
  }
  table(name: string): Observable<TableDetail> {
    return this.http.get<TableDetail>(`/api/schema/table/${encodeURIComponent(name)}`);
  }
  source(name: string, type: string): Observable<SourceCode> {
    return this.http.get<SourceCode>(`/api/schema/source/${encodeURIComponent(name)}`, { params: { type } });
  }

  // ---- query / data ----
  runSql(sql: string, maxRows?: number): Observable<QueryResult[]> {
    return this.http.post<QueryResult[]>('/api/query/run', { sql, maxRows });
  }
  browse(table: string, page: number, pageSize: number, sort?: string | null, dir?: string | null,
         filters?: ColumnFilter[]): Observable<DataPage> {
    let params = new HttpParams().set('page', page).set('pageSize', pageSize);
    if (sort) params = params.set('sort', sort).set('dir', dir || 'ASC');
    if (filters && filters.length) params = params.set('filters', JSON.stringify(filters));
    return this.http.get<DataPage>(`/api/query/data/${encodeURIComponent(table)}`, { params });
  }
  insights(table: string): Observable<Insights> {
    return this.http.get<Insights>(`/api/query/insights/${encodeURIComponent(table)}`);
  }

  pkNextInfo(table: string): Observable<Record<string, { autoGenerated: boolean; nextValue?: number }>> {
    return this.http.get<Record<string, { autoGenerated: boolean; nextValue?: number }>>(`/api/query/pk-next/${encodeURIComponent(table)}`);
  }

  insertRow(table: string, values: Record<string, any>): Observable<unknown> {
    return this.http.post(`/api/data/${encodeURIComponent(table)}`, { values });
  }
  updateRow(table: string, key: Record<string, any>, values: Record<string, any>): Observable<unknown> {
    return this.http.put(`/api/data/${encodeURIComponent(table)}`, { key, values });
  }
  deleteRow(table: string, key: Record<string, any>): Observable<unknown> {
    return this.http.request('delete', `/api/data/${encodeURIComponent(table)}`, { body: { key } });
  }

  // ---- service config ----
  listServices(params: { search?: string; status?: string; type?: string; page?: number; pageSize?: number }): Observable<ServiceListResponse> {
    let p = new HttpParams();
    if (params.search)   p = p.set('search',   params.search);
    if (params.status)   p = p.set('status',   params.status);
    if (params.type)     p = p.set('type',     params.type);
    if (params.page != null)     p = p.set('page',     params.page);
    if (params.pageSize != null) p = p.set('pageSize', params.pageSize);
    return this.http.get<ServiceListResponse>('/api/service-config', { params: p });
  }
  getService(code: string): Observable<ServiceConfigPayload> {
    return this.http.get<ServiceConfigPayload>(`/api/service-config/${encodeURIComponent(code)}`);
  }
  createService(payload: ServiceConfigPayload): Observable<unknown> {
    return this.http.post('/api/service-config', payload);
  }
  updateService(code: string, payload: ServiceConfigPayload): Observable<unknown> {
    return this.http.put(`/api/service-config/${encodeURIComponent(code)}`, payload);
  }
  deleteService(code: string): Observable<unknown> {
    return this.http.delete(`/api/service-config/${encodeURIComponent(code)}`);
  }
  saveServiceSteps(code: string, steps: StepDto[]): Observable<unknown> {
    return this.http.put(`/api/service-config/${encodeURIComponent(code)}/steps`, steps);
  }
  saveServiceFees(code: string, fees: FeeDto[]): Observable<unknown> {
    return this.http.put(`/api/service-config/${encodeURIComponent(code)}/fees`, fees);
  }
  saveServiceDocs(code: string, docs: RequiredDocDto[]): Observable<unknown> {
    return this.http.put(`/api/service-config/${encodeURIComponent(code)}/docs`, docs);
  }
  saveServiceDepts(code: string, depts: RelatedDeptDto[]): Observable<unknown> {
    return this.http.put(`/api/service-config/${encodeURIComponent(code)}/depts`, depts);
  }
  saveServiceAudience(code: string, audiences: TargetAudienceDto[]): Observable<unknown> {
    return this.http.put(`/api/service-config/${encodeURIComponent(code)}/audience`, audiences);
  }
  saveServiceConfirmation(code: string, cfgs: ConfirmationScreenConfigDto[]): Observable<unknown> {
    return this.http.put(`/api/service-config/${encodeURIComponent(code)}/confirmation`, cfgs);
  }
  nextServiceOrder(): Observable<{ nextOrder: number }> {
    return this.http.get<{ nextOrder: number }>('/api/service-config/next-order');
  }
  // Lookups
  lookupTargetAudience(): Observable<TargetAudienceLookup[]>  { return this.http.get<TargetAudienceLookup[]>('/api/service-config/lookups/audience'); }
  lookupScreenInfo(): Observable<ScreenInfoLookup[]>          { return this.http.get<ScreenInfoLookup[]>('/api/service-config/lookups/screen-info'); }
  lookupComponents(): Observable<ComponentInfoLookup[]>       { return this.http.get<ComponentInfoLookup[]>('/api/service-config/lookups/components'); }
  lookupServiceStatuses(): Observable<string[]>               { return this.http.get<string[]>('/api/service-config/lookups/statuses'); }
  lookupServiceTypes(): Observable<string[]>                  { return this.http.get<string[]>('/api/service-config/lookups/types'); }

  // ---- generic CRUD (dynamic entities) ----
  crudList(entity: string, params: { search?: string; page?: number; pageSize?: number; sort?: string; dir?: string }): Observable<CrudListResponse> {
    let p = new HttpParams();
    if (params.search)           p = p.set('search',   params.search);
    if (params.page != null)     p = p.set('page',     params.page);
    if (params.pageSize != null) p = p.set('pageSize', params.pageSize);
    if (params.sort)             p = p.set('sort',     params.sort);
    if (params.dir)              p = p.set('dir',      params.dir);
    return this.http.get<CrudListResponse>(`/api/crud/${entity}`, { params: p });
  }
  crudGet(entity: string, id: string): Observable<CrudRow> {
    return this.http.get<CrudRow>(`/api/crud/${entity}/${encodeURIComponent(id)}`);
  }
  crudCreate(entity: string, row: CrudRow): Observable<unknown> {
    return this.http.post(`/api/crud/${entity}`, row);
  }
  crudUpdate(entity: string, id: string, row: CrudRow): Observable<unknown> {
    return this.http.put(`/api/crud/${entity}/${encodeURIComponent(id)}`, row);
  }
  crudLookup(entity: string, name: string): Observable<LookupItem[]> {
    return this.http.get<LookupItem[]>(`/api/crud/${entity}/lookup/${encodeURIComponent(name)}`);
  }
  crudDelete(entity: string, id: string): Observable<unknown> {
    return this.http.delete(`/api/crud/${entity}/${encodeURIComponent(id)}`);
  }

  // ---- donation project sub-tables ----
  donationAmounts(id: number | string): Observable<Record<string,unknown>[]> {
    return this.http.get<Record<string,unknown>[]>(`/api/donation-project/${id}/amounts`);
  }
  saveDonationAmounts(id: number | string, rows: Record<string,unknown>[]): Observable<unknown> {
    return this.http.put(`/api/donation-project/${id}/amounts`, rows);
  }
  donationDetails(id: number | string): Observable<Record<string,unknown>[]> {
    return this.http.get<Record<string,unknown>[]>(`/api/donation-project/${id}/details`);
  }
  saveDonationDetails(id: number | string, rows: Record<string,unknown>[]): Observable<unknown> {
    return this.http.put(`/api/donation-project/${id}/details`, rows);
  }

  // ---- attachments ----
  uploadAttachment(file: File, folder: string, documentName: string): Observable<HttpEvent<UploadResult>> {
    const form = new FormData();
    form.append('file', file);
    form.append('folder', folder);
    form.append('documentName', documentName);
    return this.http.post<UploadResult>('/api/attachments/upload', form, {
      headers: { 'X-Requested-With': 'XMLHttpRequest' },
      reportProgress: true,
      observe: 'events',
    });
  }

  // ---- admin ----
  listUsers(): Observable<AdminUserSummary[]> {
    return this.http.get<AdminUserSummary[]>('/api/admin/users');
  }
  getUser(username: string): Observable<AdminUserDetail> {
    return this.http.get<AdminUserDetail>(`/api/admin/user/${encodeURIComponent(username)}`);
  }
  saveUser(body: SaveUserRequest): Observable<void> {
    return this.http.post<void>('/api/admin/user', body);
  }
  deleteUser(username: string): Observable<void> {
    return this.http.delete<void>(`/api/admin/user/${encodeURIComponent(username)}`);
  }
}
